// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weavers.Core;

#nullable disable

namespace Weavers.Core.Migrations
{
    [DbContext(typeof(FabricDbContext))]
    [Migration("20260414175636_AddDefaultsUpdateX2")]
    partial class AddDefaultsUpdateX2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weavers.Core.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Weavers.Core.Entities.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Boolean (true/false)",
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 2,
                            Description = "16-bit integer",
                            Name = "Int16"
                        },
                        new
                        {
                            Id = 3,
                            Description = "32-bit integer",
                            Name = "Int32"
                        },
                        new
                        {
                            Id = 4,
                            Description = "64-bit integer",
                            Name = "Int64"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Globally Unique Identifier",
                            Name = "Guid"
                        },
                        new
                        {
                            Id = 6,
                            Description = "ASCII string",
                            Name = "StrAscii"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Unicode string",
                            Name = "StrUnicode"
                        },
                        new
                        {
                            Id = 8,
                            Description = "32-bit floating point number",
                            Name = "Float32"
                        },
                        new
                        {
                            Id = 9,
                            Description = "64-bit floating point number",
                            Name = "Float64"
                        },
                        new
                        {
                            Id = 10,
                            Description = "128-bit decimal number",
                            Name = "Decimal128"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Date (year, month, day)",
                            Name = "Date"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Time (hour, minute, second)",
                            Name = "Time"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Small date and time (1900-01-01 to 2079-06-06)",
                            Name = "SmallDateTime"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Date and time (1753-01-01 to 9999-12-31)",
                            Name = "DateTime"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Date and time with larger range and precision than DateTime",
                            Name = "DateTime2"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Date and time with time zone awareness",
                            Name = "DateTimeOffset"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Binary data (byte array)",
                            Name = "Binary"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Reference to Items graph see ReferenceItemTypeId for Item Properties",
                            Name = "Reference"
                        },
                        new
                        {
                            Id = -1,
                            Description = "None",
                            Name = "None"
                        });
                });

            modelBuilder.Entity("Weavers.Core.Entities.EditorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EditorTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "No editor",
                            IconName = "",
                            IsReadOnly = true,
                            IsVisible = false,
                            Name = "None",
                            Rank = 0
                        },
                        new
                        {
                            Id = 1,
                            Description = "Hidden editor",
                            IconName = "pi-eye-slash",
                            IsReadOnly = true,
                            IsVisible = false,
                            Name = "Hidden",
                            Rank = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Boolean editor",
                            IconName = "pi-check",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Boolean",
                            Rank = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Integer editor",
                            IconName = "pi-pencil",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Integer",
                            Rank = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "String editor",
                            IconName = "pi-pencil",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "String",
                            Rank = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "File name editor",
                            IconName = "pi-file",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "FileName",
                            Rank = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "Date editor",
                            IconName = "pi-calendar",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Date",
                            Rank = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Time editor",
                            IconName = "pi-clock",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Time",
                            Rank = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Decimal editor",
                            IconName = "pi-dollar",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Decimal",
                            Rank = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Password editor",
                            IconName = "pi-lock",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Password",
                            Rank = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lookup type editor",
                            IconName = "pi-search",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Lookup Type Editor",
                            Rank = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lookup model editor",
                            IconName = "pi-search",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Lookup Model Editor",
                            Rank = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Memo editor",
                            IconName = "pi-pencil",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Memo",
                            Rank = 0
                        },
                        new
                        {
                            Id = 13,
                            Description = "Folder editor",
                            IconName = "pi-folder",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Folder",
                            Rank = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Relative folder editor",
                            IconName = "pi-folder",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "Relative Folder",
                            Rank = 0
                        },
                        new
                        {
                            Id = 15,
                            Description = "URL editor",
                            IconName = "pi-link",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "URL",
                            Rank = 0
                        });
                });

            modelBuilder.Entity("Weavers.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EditorTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemPropertyDefaultId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReferenceItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValueDataTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorTypeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemPropertyDefaultId");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceItemTypeId");

                    b.HasIndex("ValueDataTypeId");

                    b.HasIndex("ItemId", "Name")
                        .IsUnique();

                    b.ToTable("ItemProperties");
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemPropertyDefault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("EditorTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ReferenceItemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ValueDataTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorTypeId");

                    b.HasIndex("ReferenceItemTypeId");

                    b.HasIndex("ValueDataTypeId");

                    b.HasIndex("ItemTypeId", "Key")
                        .IsUnique();

                    b.ToTable("ItemPropertyDefaults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultValue = "",
                            EditorTypeId = 13,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 100,
                            Key = "RootFolder",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 2,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 100,
                            Key = "RepositoryUrl",
                            Rank = 2,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 3,
                            DefaultValue = "",
                            EditorTypeId = 14,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 110,
                            Key = "RelativeFolder",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 4,
                            DefaultValue = "",
                            EditorTypeId = 5,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 150,
                            Key = "FilePath",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 5,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 200,
                            Key = "FilePath",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 6,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 300,
                            Key = "FilePath",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 400,
                            Key = "FilePath",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 8,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 420,
                            Key = "BaseType",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 9,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 422,
                            Key = "PropertyType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 422,
                            Key = "IsNullable",
                            Rank = 2,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 424,
                            Key = "ReturnType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 426,
                            Key = "ParameterType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 426,
                            Key = "IsNullable",
                            Rank = 2,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 440,
                            Key = "Namespace",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 15,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 440,
                            Key = "BaseType",
                            Rank = 2,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 440,
                            Key = "Interface",
                            Rank = 3,
                            ReferenceItemTypeId = 420,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            DefaultValue = "",
                            EditorTypeId = 12,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 440,
                            Key = "RecordContent",
                            Rank = 4,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 18,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 460,
                            Key = "Namespace",
                            Rank = 1,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 19,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 460,
                            Key = "BaseType",
                            Rank = 2,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 460,
                            Key = "Interface",
                            Rank = 3,
                            ReferenceItemTypeId = 420,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 21,
                            DefaultValue = "",
                            EditorTypeId = 12,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 460,
                            Key = "StructContent",
                            Rank = 4,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 22,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 500,
                            Key = "Namespace",
                            Rank = 1,
                            ReferenceItemTypeId = 420,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 23,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 500,
                            Key = "BaseType",
                            Rank = 2,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            DefaultValue = "",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 500,
                            Key = "Interface",
                            Rank = 3,
                            ReferenceItemTypeId = 420,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 25,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 522,
                            Key = "PropertyType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 522,
                            Key = "PropertyTypeRefName",
                            Rank = 2,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 27,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 522,
                            Key = "IsNullable",
                            Rank = 3,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "ReturnType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "ReturnTypeRefName",
                            Rank = 2,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 30,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "IsAsync",
                            Rank = 3,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "IsVirtual",
                            Rank = 4,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "IsStatic",
                            Rank = 5,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "IsAbstract",
                            Rank = 6,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 524,
                            Key = "IsSealed",
                            Rank = 7,
                            ValueDataTypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            DefaultValue = "64",
                            EditorTypeId = 10,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 526,
                            Key = "ParameterType",
                            Rank = 1,
                            ReferenceItemTypeId = 50,
                            ValueDataTypeId = 3
                        },
                        new
                        {
                            Id = 36,
                            DefaultValue = "",
                            EditorTypeId = 4,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 526,
                            Key = "ParameterTypeRefName",
                            Rank = 2,
                            ValueDataTypeId = 6
                        },
                        new
                        {
                            Id = 37,
                            DefaultValue = "1",
                            EditorTypeId = 2,
                            IsReadOnly = false,
                            IsRequired = false,
                            IsVisible = true,
                            ItemTypeId = 526,
                            Key = "IsNullable",
                            Rank = 3,
                            ValueDataTypeId = 1
                        });
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EditorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentTypeId");

                    b.HasIndex("ParentTypeId", "Rank");

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Description = "Owner Type of SQL Types",
                            EditorTypeId = 10,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlTypes",
                            Rank = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "sql bit type",
                            EditorTypeId = 2,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlBitType",
                            ParentTypeId = 10,
                            Rank = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "sql smallint type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlSmallIntType",
                            ParentTypeId = 10,
                            Rank = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "sql int type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlIntType",
                            ParentTypeId = 10,
                            Rank = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "sql bigint type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlBigIntType",
                            ParentTypeId = 10,
                            Rank = 5
                        },
                        new
                        {
                            Id = 16,
                            Description = "sql uniqueidentifier type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlGuidType",
                            ParentTypeId = 10,
                            Rank = 6
                        },
                        new
                        {
                            Id = 18,
                            Description = "sql varchar type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlVarcharType",
                            ParentTypeId = 10,
                            Rank = 7
                        },
                        new
                        {
                            Id = 20,
                            Description = "sql nvarchar type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlNVarcharType",
                            ParentTypeId = 10,
                            Rank = 8
                        },
                        new
                        {
                            Id = 21,
                            Description = "sql float type",
                            EditorTypeId = -1,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlFloatType",
                            ParentTypeId = 21,
                            Rank = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "sql decimal type",
                            EditorTypeId = 8,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlDecimalType",
                            ParentTypeId = 10,
                            Rank = 9
                        },
                        new
                        {
                            Id = 24,
                            Description = "sql datetime type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlDateTimeType",
                            ParentTypeId = 10,
                            Rank = 10
                        },
                        new
                        {
                            Id = 25,
                            Description = "sql datetime2 type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlDateTime2Type",
                            ParentTypeId = 10,
                            Rank = 11
                        },
                        new
                        {
                            Id = 26,
                            Description = "sql date type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlDateType",
                            ParentTypeId = 10,
                            Rank = 12
                        },
                        new
                        {
                            Id = 28,
                            Description = "sql time type",
                            EditorTypeId = 7,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlTimeType",
                            ParentTypeId = 10,
                            Rank = 13
                        },
                        new
                        {
                            Id = 29,
                            Description = "sql datetimeoffset type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlDateTimeOffsetType",
                            ParentTypeId = 10,
                            Rank = 14
                        },
                        new
                        {
                            Id = 30,
                            Description = "sql binary type",
                            EditorTypeId = -1,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "SqlBinaryType",
                            ParentTypeId = 10,
                            Rank = 15
                        },
                        new
                        {
                            Id = 50,
                            Description = "Owner Type of C# Types",
                            EditorTypeId = 10,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpTypes",
                            Rank = 1
                        },
                        new
                        {
                            Id = 52,
                            Description = "C# Class Type",
                            EditorTypeId = 11,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpClassType",
                            ParentTypeId = 50,
                            Rank = 2
                        },
                        new
                        {
                            Id = 54,
                            Description = "C# Record Type",
                            EditorTypeId = 11,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpRecordType",
                            ParentTypeId = 50,
                            Rank = 3
                        },
                        new
                        {
                            Id = 56,
                            Description = "C# Struct Type",
                            EditorTypeId = 11,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpStructType",
                            ParentTypeId = 50,
                            Rank = 4
                        },
                        new
                        {
                            Id = 58,
                            Description = "C# String Type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpStringType",
                            ParentTypeId = 50,
                            Rank = 5
                        },
                        new
                        {
                            Id = 60,
                            Description = "C# Bool Type",
                            EditorTypeId = 2,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpBoolType",
                            ParentTypeId = 50,
                            Rank = 6
                        },
                        new
                        {
                            Id = 62,
                            Description = "C# Char Type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpCharType",
                            ParentTypeId = 50,
                            Rank = 7
                        },
                        new
                        {
                            Id = 64,
                            Description = "C# Int Type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpIntType",
                            ParentTypeId = 50,
                            Rank = 8
                        },
                        new
                        {
                            Id = 66,
                            Description = "C# Long Type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpLongType",
                            ParentTypeId = 50,
                            Rank = 9
                        },
                        new
                        {
                            Id = 68,
                            Description = "C# Short Type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpShortType",
                            ParentTypeId = 50,
                            Rank = 10
                        },
                        new
                        {
                            Id = 70,
                            Description = "C# Decimal Type",
                            EditorTypeId = 8,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDecimalType",
                            ParentTypeId = 50,
                            Rank = 11
                        },
                        new
                        {
                            Id = 72,
                            Description = "C# Double Type",
                            EditorTypeId = 8,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDoubleType",
                            ParentTypeId = 50,
                            Rank = 12
                        },
                        new
                        {
                            Id = 74,
                            Description = "C# Float Type",
                            EditorTypeId = 8,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpFloatType",
                            ParentTypeId = 50,
                            Rank = 13
                        },
                        new
                        {
                            Id = 76,
                            Description = "C# Byte Type",
                            EditorTypeId = 3,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpByteType",
                            ParentTypeId = 50,
                            Rank = 14
                        },
                        new
                        {
                            Id = 78,
                            Description = "C# DateTime Type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDateTimeType",
                            ParentTypeId = 50,
                            Rank = 15
                        },
                        new
                        {
                            Id = 79,
                            Description = "C# DateTime2 Type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDateTime2Type",
                            ParentTypeId = 50,
                            Rank = 16
                        },
                        new
                        {
                            Id = 80,
                            Description = "C# Date Type",
                            EditorTypeId = 6,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDateType",
                            ParentTypeId = 50,
                            Rank = 17
                        },
                        new
                        {
                            Id = 82,
                            Description = "C# Time Type",
                            EditorTypeId = 7,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpTimeType",
                            ParentTypeId = 50,
                            Rank = 18
                        },
                        new
                        {
                            Id = 84,
                            Description = "C# DateTimeOffset Type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpDateTimeOffsetType",
                            ParentTypeId = 50,
                            Rank = 19
                        },
                        new
                        {
                            Id = 86,
                            Description = "C# Byte Array Type",
                            EditorTypeId = -1,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpByteArrayType",
                            ParentTypeId = 50,
                            Rank = 20
                        },
                        new
                        {
                            Id = 88,
                            Description = "C# Guid Type",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "CSharpGuidType",
                            ParentTypeId = 50,
                            Rank = 21
                        },
                        new
                        {
                            Id = 100,
                            Description = "Project Folder",
                            EditorTypeId = 4,
                            IconName = "pi pi-folder",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "ProjectFolderModel",
                            Rank = 100
                        },
                        new
                        {
                            Id = 110,
                            Description = "Relative Folder",
                            EditorTypeId = 4,
                            IconName = "pi pi-folder",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "RelativeFolderModel",
                            ParentTypeId = 100,
                            Rank = 110
                        },
                        new
                        {
                            Id = 150,
                            Description = "File",
                            EditorTypeId = 5,
                            IconName = "pi pi-file",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "FileModel",
                            ParentTypeId = 110,
                            Rank = 150
                        },
                        new
                        {
                            Id = 200,
                            Description = "Library",
                            EditorTypeId = 4,
                            IconName = "pi pi-book",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "LibraryModel",
                            ParentTypeId = 110,
                            Rank = 200
                        },
                        new
                        {
                            Id = 300,
                            Description = "Dependency Injection",
                            EditorTypeId = 4,
                            IconName = "pi pi-cog",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "DependencyInjectionModel",
                            ParentTypeId = 200,
                            Rank = 300
                        },
                        new
                        {
                            Id = 302,
                            Description = "DI - DbContext",
                            EditorTypeId = 4,
                            IconName = "pi pi-database",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "DiDbContextModel",
                            ParentTypeId = 300,
                            Rank = 302
                        },
                        new
                        {
                            Id = 304,
                            Description = "DI - Mediator",
                            EditorTypeId = 4,
                            IconName = "pi pi-cogs",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "DiMediatorModel",
                            ParentTypeId = 300,
                            Rank = 304
                        },
                        new
                        {
                            Id = 400,
                            Description = "Namespace",
                            EditorTypeId = 4,
                            IconName = "pi pi-globe",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "NamespaceModel",
                            ParentTypeId = 150,
                            Rank = 400
                        },
                        new
                        {
                            Id = 420,
                            Description = "Interface",
                            EditorTypeId = 4,
                            IconName = "pi pi-plug",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "InterfaceModel",
                            ParentTypeId = 400,
                            Rank = 420
                        },
                        new
                        {
                            Id = 422,
                            Description = "Interface Property",
                            EditorTypeId = 4,
                            IconName = "pi pi-plug",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "InterfacePropertyModel",
                            ParentTypeId = 420,
                            Rank = 422
                        },
                        new
                        {
                            Id = 424,
                            Description = "Interface Method",
                            EditorTypeId = 4,
                            IconName = "pi pi-plug",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "InterfaceMethodModel",
                            ParentTypeId = 420,
                            Rank = 424
                        },
                        new
                        {
                            Id = 426,
                            Description = "Interface Method Parameter",
                            EditorTypeId = 4,
                            IconName = "pi pi-plug",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "InterfaceMethodParameterModel",
                            ParentTypeId = 424,
                            Rank = 426
                        },
                        new
                        {
                            Id = 440,
                            Description = "Record",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "RecordModel",
                            ParentTypeId = 400,
                            Rank = 440
                        },
                        new
                        {
                            Id = 460,
                            Description = "Struct",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "StructModel",
                            ParentTypeId = 400,
                            Rank = 460
                        },
                        new
                        {
                            Id = 500,
                            Description = "Class",
                            EditorTypeId = 4,
                            IconName = "pi pi-cubes",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "ClassModel",
                            ParentTypeId = 400,
                            Rank = 500
                        },
                        new
                        {
                            Id = 522,
                            Description = "Class Property",
                            EditorTypeId = 4,
                            IconName = "pi pi-cube",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "ClassPropertyModel",
                            ParentTypeId = 500,
                            Rank = 522
                        },
                        new
                        {
                            Id = 524,
                            Description = "Class Method",
                            EditorTypeId = 4,
                            IconName = "pi pi-cube",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "ClassMethodModel",
                            ParentTypeId = 500,
                            Rank = 524
                        },
                        new
                        {
                            Id = 526,
                            Description = "Class Method Parameter",
                            EditorTypeId = 4,
                            IconName = "pi pi-cube",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "ClassMethodParameterModel",
                            ParentTypeId = 524,
                            Rank = 526
                        },
                        new
                        {
                            Id = 600,
                            Description = "Entity",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityModel",
                            ParentTypeId = 400,
                            Rank = 600
                        },
                        new
                        {
                            Id = 610,
                            Description = "Entity Class",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityClassModel",
                            ParentTypeId = 600,
                            Rank = 610
                        },
                        new
                        {
                            Id = 612,
                            Description = "Entity Property",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityPropertyModel",
                            ParentTypeId = 600,
                            Rank = 612
                        },
                        new
                        {
                            Id = 614,
                            Description = "Entity Navigation Property",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityNavigationModel",
                            ParentTypeId = 600,
                            Rank = 614
                        },
                        new
                        {
                            Id = 620,
                            Description = "Entity Configuration Class",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityConfigurationModel",
                            ParentTypeId = 600,
                            Rank = 620
                        },
                        new
                        {
                            Id = 622,
                            Description = "Entity Property Configuration",
                            EditorTypeId = 4,
                            IconName = "",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "EntityPropertyConfigurationModel",
                            ParentTypeId = 612,
                            Rank = 622
                        },
                        new
                        {
                            Id = 700,
                            Description = "Handler",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerModel",
                            ParentTypeId = 400,
                            Rank = 700
                        },
                        new
                        {
                            Id = 710,
                            Description = "Handler Response",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerResponseModel",
                            ParentTypeId = 700,
                            Rank = 710
                        },
                        new
                        {
                            Id = 720,
                            Description = "Handler Command",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerCommandModel",
                            ParentTypeId = 700,
                            Rank = 720
                        },
                        new
                        {
                            Id = 730,
                            Description = "Handler Class",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerClassModel",
                            ParentTypeId = 700,
                            Rank = 730
                        },
                        new
                        {
                            Id = 732,
                            Description = "Handler Property",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerPropertyModel",
                            ParentTypeId = 730,
                            Rank = 732
                        },
                        new
                        {
                            Id = 734,
                            Description = "Handler Method",
                            EditorTypeId = 4,
                            IconName = "pi pi-shield",
                            IsReadOnly = false,
                            IsVisible = true,
                            Name = "HandlerMethodModel",
                            ParentTypeId = 730,
                            Rank = 734
                        });
                });

            modelBuilder.Entity("Weavers.Core.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("int");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedItemId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("ItemId", "RelationTypeId", "RelatedItemId")
                        .IsUnique()
                        .HasFilter("[RelatedItemId] IS NOT NULL");

                    b.ToTable("Relations", (string)null);
                });

            modelBuilder.Entity("Weavers.Core.Entities.RelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Description = "Item belongs to a type category",
                            Name = "TypeOf"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Structural parent contains child model",
                            Name = "Contains"
                        });
                });

            modelBuilder.Entity("Weavers.Core.Entities.Item", b =>
                {
                    b.HasOne("Weavers.Core.Entities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemProperty", b =>
                {
                    b.HasOne("Weavers.Core.Entities.EditorType", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.Item", "Item")
                        .WithMany("Properties")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Weavers.Core.Entities.ItemPropertyDefault", "ItemPropertyDefault")
                        .WithMany()
                        .HasForeignKey("ItemPropertyDefaultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.ItemType", "ReferenceItemType")
                        .WithMany()
                        .HasForeignKey("ReferenceItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.DataType", "ValueType")
                        .WithMany()
                        .HasForeignKey("ValueDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Editor");

                    b.Navigation("Item");

                    b.Navigation("ItemPropertyDefault");

                    b.Navigation("ReferenceItemType");

                    b.Navigation("ValueType");
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemPropertyDefault", b =>
                {
                    b.HasOne("Weavers.Core.Entities.EditorType", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.ItemType", "ItemType")
                        .WithMany("PropertyDefaults")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Weavers.Core.Entities.ItemType", "ReferenceItemType")
                        .WithMany()
                        .HasForeignKey("ReferenceItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.DataType", "ValueDataType")
                        .WithMany()
                        .HasForeignKey("ValueDataTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Editor");

                    b.Navigation("ItemType");

                    b.Navigation("ReferenceItemType");

                    b.Navigation("ValueDataType");
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemType", b =>
                {
                    b.HasOne("Weavers.Core.Entities.EditorType", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Weavers.Core.Entities.ItemType", "ParentType")
                        .WithMany("ChildTypes")
                        .HasForeignKey("ParentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Editor");

                    b.Navigation("ParentType");
                });

            modelBuilder.Entity("Weavers.Core.Entities.Relation", b =>
                {
                    b.HasOne("Weavers.Core.Entities.Item", "Item")
                        .WithMany("Relations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Weavers.Core.Entities.Item", "RelatedItem")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Weavers.Core.Entities.RelationType", "RelationType")
                        .WithMany("Relations")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("Weavers.Core.Entities.Item", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("Properties");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("Weavers.Core.Entities.ItemType", b =>
                {
                    b.Navigation("ChildTypes");

                    b.Navigation("Items");

                    b.Navigation("PropertyDefaults");
                });

            modelBuilder.Entity("Weavers.Core.Entities.RelationType", b =>
                {
                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
