// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weavers.Core;

#nullable disable

namespace Weavers.Core.Migrations
{
    [DbContext(typeof(FabricDbContext))]
    [Migration("20260404041222_AddsWeaversInitialCreate")]
    partial class AddsWeaversInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("int");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedItemId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("ItemId", "RelationTypeId", "RelatedItemId")
                        .IsUnique()
                        .HasFilter("[RelatedItemId] IS NOT NULL");

                    b.ToTable("ItemRelations", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Relation")
                        .IsUnique();

                    b.ToTable("ItemRelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Description = "Idea → Idea / Idea → Requirement",
                            Relation = "INSPIRES"
                        },
                        new
                        {
                            Id = 201,
                            Description = "Requirement → Idea",
                            Relation = "ADDRESSES"
                        },
                        new
                        {
                            Id = 202,
                            Description = "ResearchFinding → Idea / Requirement",
                            Relation = "REFINES"
                        },
                        new
                        {
                            Id = 203,
                            Description = "Constraint → Idea / Requirement / Capability",
                            Relation = "CONSTRAINS"
                        },
                        new
                        {
                            Id = 204,
                            Description = "ResearchFinding / PoC → Requirement / Capability",
                            Relation = "VALIDATES"
                        },
                        new
                        {
                            Id = 205,
                            Description = "Decision → Constraint",
                            Relation = "RESOLVES"
                        },
                        new
                        {
                            Id = 206,
                            Description = "Capability → Requirement / Feature",
                            Relation = "ENABLES"
                        },
                        new
                        {
                            Id = 207,
                            Description = "Constraint → Capability",
                            Relation = "LIMITS"
                        },
                        new
                        {
                            Id = 208,
                            Description = "Requirement / Feature → Capability",
                            Relation = "DEPENDS_ON"
                        },
                        new
                        {
                            Id = 209,
                            Description = "Capability → Capability (stack evolution)",
                            Relation = "EXTENDS"
                        },
                        new
                        {
                            Id = 210,
                            Description = "Previous Layer / Artifact → Next Layer",
                            Relation = "BUILDS_ON"
                        },
                        new
                        {
                            Id = 211,
                            Description = "Agent → Artifact / Layer / Requirement",
                            Relation = "PRODUCES"
                        },
                        new
                        {
                            Id = 212,
                            Description = "Agent → ResearchFinding / Capability",
                            Relation = "CONSUMES"
                        },
                        new
                        {
                            Id = 213,
                            Description = "Orchestrator / Layer → Agent",
                            Relation = "ASSIGNS_TO"
                        },
                        new
                        {
                            Id = 214,
                            Description = "Agent → Command / Handler",
                            Relation = "EXECUTES"
                        },
                        new
                        {
                            Id = 215,
                            Description = "Handler → Command / Query",
                            Relation = "IMPLEMENTS"
                        },
                        new
                        {
                            Id = 216,
                            Description = "Core / MediatR → ClientApp",
                            Relation = "EXPOSES_TO"
                        },
                        new
                        {
                            Id = 217,
                            Description = "Handler → Command / Query",
                            Relation = "HANDLES"
                        },
                        new
                        {
                            Id = 218,
                            Description = "Command → Handler",
                            Relation = "TRIGGERS"
                        },
                        new
                        {
                            Id = 219,
                            Description = "Handler → DomainEntity",
                            Relation = "RETURNS"
                        },
                        new
                        {
                            Id = 220,
                            Description = "ClientApp → Command / Query",
                            Relation = "USES"
                        },
                        new
                        {
                            Id = 221,
                            Description = "DomainEntity → DomainEntity (relationships)",
                            Relation = "BELONGS_TO"
                        },
                        new
                        {
                            Id = 222,
                            Description = "Feature / Requirement → DomainEntity / Handler",
                            Relation = "REQUIRES"
                        },
                        new
                        {
                            Id = 223,
                            Description = "LessonLearned → Capability / Decision",
                            Relation = "INFORMS"
                        },
                        new
                        {
                            Id = 224,
                            Description = "PoC / Experiment → LessonLearned / Requirement",
                            Relation = "RESULTS_IN"
                        },
                        new
                        {
                            Id = 225,
                            Description = "Container → Item (Layer → Feature, etc.)",
                            Relation = "CONTAINS"
                        },
                        new
                        {
                            Id = 226,
                            Description = "Artifact → Requirement / Idea",
                            Relation = "DERIVES_FROM"
                        },
                        new
                        {
                            Id = 227,
                            Description = "Loose reference between any two items",
                            Relation = "REFERENCES"
                        },
                        new
                        {
                            Id = 228,
                            Description = "Sequencing: Layer A precedes Layer B",
                            Relation = "PRECEDES"
                        },
                        new
                        {
                            Id = 229,
                            Description = "Sequencing: Layer B follows Layer A",
                            Relation = "FOLLOWS"
                        });
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Description = "Raw product ideas or chicken-and-egg problems (starting point)",
                            Name = "Idea"
                        },
                        new
                        {
                            Id = 101,
                            Description = "What the stack, agents, or developer can currently do reliably",
                            Name = "Capability"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Scope, tech, time, or client-type limitations",
                            Name = "Constraint"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Functional or non-functional specifications / user stories",
                            Name = "Requirement"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Market, competitor, feasibility, or validation insights",
                            Name = "ResearchFinding"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Business domain object in the app (e.g. Task, Record)",
                            Name = "DomainEntity"
                        },
                        new
                        {
                            Id = 106,
                            Description = "MediatR command (e.g. CreateTaskCommand)",
                            Name = "Command"
                        },
                        new
                        {
                            Id = 107,
                            Description = "MediatR query",
                            Name = "Query"
                        },
                        new
                        {
                            Id = 108,
                            Description = "MediatR command/query handler",
                            Name = "Handler"
                        },
                        new
                        {
                            Id = 109,
                            Description = "WinFormsClient, AngularClient, ConsoleTester, etc.",
                            Name = "ClientApp"
                        },
                        new
                        {
                            Id = 110,
                            Description = "AI agent role (ResearchAgent, LayerBuilderAgent, etc.)",
                            Name = "Agent"
                        },
                        new
                        {
                            Id = 111,
                            Description = "Build layer in the agent chain (RequirementsLayer, InfraLayer, etc.)",
                            Name = "Layer"
                        },
                        new
                        {
                            Id = 112,
                            Description = "Scoped feature or user story",
                            Name = "Feature"
                        },
                        new
                        {
                            Id = 113,
                            Description = "Architectural or scoping decision with rationale",
                            Name = "Decision"
                        },
                        new
                        {
                            Id = 114,
                            Description = "Post-iteration insights and capability updates",
                            Name = "LessonLearned"
                        },
                        new
                        {
                            Id = 115,
                            Description = "Generated output (code snippet, diagram, mock, document)",
                            Name = "Artifact"
                        },
                        new
                        {
                            Id = 116,
                            Description = "Proof-of-concept experiment or vertical slice",
                            Name = "PoC"
                        });
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.HasOne("KB.Core.Entities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.HasOne("KB.Core.Entities.Item", "Item")
                        .WithMany("Relations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KB.Core.Entities.Item", "RelatedItem")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KB.Core.Entities.ItemRelationType", "RelationType")
                        .WithMany("ItemRelations")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Navigation("ItemRelations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
